### ISSUE TITLE
Feature Request: 能否实现像obsidian-aloud-tts插件那样, 明确的标注正在阅读的区域

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#82]
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/2c87ec71-0678-4834-8c77-e11f8b4e033a)
obsidian-aloud-tts插件和text2audio类似, 但是它有一个很好的功能, 当播放器在播放时, 会明确的指示正在阅读哪一行的文字, 并且通过css的snippets, 可以对读过的文字和未读过的文字进行区分, 截图那里只对阅读的区域进行区分是因为我修改了css snippets

麻烦作者尝试一下这个插件, 这个插件需要用到OpenAI的API key, 为了方便你测试, 我发我的API key发到你的这个邮箱: youzui@hotmail.com, 看看text2audio能否实现类似的功能, 谢谢作者!

```css
.tts-cm-playing-before,
.tts-cm-playing-after {
  background-color: rgba(var(--color-red-rgb), 0) !important;
}

.tts-cm-playing-now {
  background-color: rgba(248, 240, 10, 0.2) !important;
}
```
